/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcSlidingPanel {
    'position': "left" | "right";
    'toggled': boolean;
  }
}

declare global {


  interface HTMLPwcSlidingPanelElement extends Components.PwcSlidingPanel, HTMLStencilElement {}
  var HTMLPwcSlidingPanelElement: {
    prototype: HTMLPwcSlidingPanelElement;
    new (): HTMLPwcSlidingPanelElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-sliding-panel': HTMLPwcSlidingPanelElement;
  }
}

declare namespace LocalJSX {
  interface PwcSlidingPanel {
    'position'?: "left" | "right";
    'toggled'?: boolean;
  }

  interface IntrinsicElements {
    'pwc-sliding-panel': PwcSlidingPanel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-sliding-panel': LocalJSX.PwcSlidingPanel & JSXBase.HTMLAttributes<HTMLPwcSlidingPanelElement>;
    }
  }
}


